server:
  port: 8082

services:
  auth:
    url: http://localhost:8081
  product:
    url: http://localhost:8085

eureka:
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:change-me-in-production-please-use-a-32+char-secret!}

management:
  endpoints:
    web:
      exposure:
        include: "*"
