#server:
#  port: 8085
#
#spring:
#  application:
#    name: admin-service
#
#  config:
#    import: "optional:configserver:"
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#services:
#  auth:
#    url: http://auth-service
#  product:
#    url: http://product-service
#  order:
#    url: http://order-service

spring:
  application:
    name: admin-service

  config:
    import: configserver:http://localhost:8888

jwt:
  secret: ${JWT_SECRET:change-me-in-production-please-use-a-32+char-secret!}

internal:
  service:
    key: ${INTERNAL_SERVICE_KEY:change-me-in-production}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
