server:
  port: 8080

spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      server:
        webmvc:
          routes:

            # Auth Service
            - id: auth-service-auth
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**

            - id: auth-service-users
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/users/**

            # Customer Service
            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/customers/**

            # Admin Service
            - id: admin-service
              uri: lb://ADMIN-SERVICE
              predicates:
                - Path=/admin/**

            # Product Service
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/products/**

            # Category APIs (if inside Product Service)
            - id: category-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/categories/**

            - id: subcategory-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/subcategories/**

            # Cart Service
            - id: cart-service
              uri: lb://CART-SERVICE
              predicates:
                - Path=/cart/**

            # Wishlist Service
            - id: wishlist-service
              uri: lb://WISHLIST-SERVICE
              predicates:
                - Path=/wishlist/**

            # Seller Service
            - id: seller-service
              uri: lb://SELLER-SERVICE
              predicates:
                - Path=/sellers/**
      

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:change-me-in-production-please-use-a-32+char-secret!}

services:
  auth:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}

internal:
  service:
    key: ${INTERNAL_SERVICE_KEY:change-me-in-production}
